#+TITLE: Jeff's Dotfiles

* Table of Contents :toc:
- [[#what-are-dotfiles][What Are Dotfiles?]]
- [[#how-to-manage-your-own-dotfiles][How To Manage Your Own Dotfiles]]
- [[#license][License]]

* What Are Dotfiles?

Dotfiles are customization files used by Linux and other Unix-based systems.
Their name will begin with a period (dot), since the term “dot file”. The dot at
the begining of the name indicates that this is hidden file or directory. This
repository contains my personal dotfiles.


* How To Manage Your Own Dotfiles

There are many possible ways to handle dotfiles. I use the *git bare repository
method* for managing my dotfiles. Here is an article about this method of
managing your dotfiles:
[[https://developer.atlassian.com/blog/2016/02/best-way-to-store-dotfiles-git-bare-repo/][https://developer.atlassian.com/blog/2016/02/best-way-to-store-dotfiles-git-bare-repo/]]


* License

The files and scripts in this repository are licensed under the MIT License,
which is a very permissive license allowing you to use, modify, copy,
distribute, sell, give away, etc. the software. In other words, do what you want
with it. The only requirement with the MIT License is that the license and
copyright notice must be provided with the software.
